### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [omar/mesoBoard#1]
Hi @omar 

I was wondering may I use some this code in my project which is a basic alliance management with forum if I may would you like me to provide credits?

**Comment by omar** [comment]
Hello @di48l069, feel free to use the code. However, I haven't touched the code in a long time so it's using an older version of MVC. You might want to also look at [Mvc Forum](https://github.com/YodasMyDad/mvcforum) which used the mesoBoard codebase early on.

**Comment by ghost** [comment]
Thank you, I will have a look at MVC Forum, Would you like me to provide any credits

**Comment by omar** [comment]
A link to this GitHub repo somewhere should be enough.
